'use client';

import { useEffect, useState } from 'react';
import { AppShell } from '@/components/AppShell';
import { Alert } from '@/components/Common/Alert';
import { Button } from '@/components/Common/Button';
import { useProtectedRoute } from '@/hooks/useAuth';
import { authApi } from '@/lib/api';

interface PracticeQuestion { type: 'multiple_choice' | 'essay'; questionText: string; options?: string[]; correctOptionIndex?: number; answer?: string; points?: number; }
interface PracticeResult { score: number; maxScore: number; percentage: number; results: Array<{ correct: boolean; matchPercentage: number; awardedPoints: number; maxPoints: number; explanation: string }> }

export default function StudentSubjectsPage() {
  const { isAuthenticated } = useProtectedRoute();
  const [dashboard, setDashboard] = useState<any>(null);
  const [practice, setPractice] = useState<{ lesson: { title: string }; questions: PracticeQuestion[] } | null>(null);
  const [answers, setAnswers] = useState<Record<number, string>>({});
  const [result, setResult] = useState<PracticeResult | null>(null);
  const [study, setStudy] = useState<{ title: string; url: string; type: 'youtube' | 'pdf' } | null>(null);
  const [error, setError] = useState('');
  const [aiLoading, setAiLoading] = useState(false);

  useEffect(() => { if (isAuthenticated) void authApi.student.dashboard().then(setDashboard).catch((reason: any) => setError(reason.message || 'Gagal memuat mata pelajaran.')); }, [isAuthenticated]);
  const youtubeId = (source?: string) => source?.match(/(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([a-zA-Z0-9_-]{11})/)?.[1] || null;
  const openPractice = async (lessonId: string) => { setAiLoading(true); setResult(null); setAnswers({}); try { setPractice(await authApi.student.generateLessonPractice(lessonId)); } catch (reason: any) { setError(reason.message || 'Gagal membuat latihan AI.'); } finally { setAiLoading(false); } };
  const gradePractice = async () => { if (!practice) return; setAiLoading(true); try { setResult(await authApi.student.gradeLessonPractice(practice.questions, answers)); } catch (reason: any) { setError(reason.message || 'Gagal memeriksa jawaban dengan AI.'); } finally { setAiLoading(false); } };
  const closePractice = () => { setPractice(null); setResult(null); setAnswers({}); };

  if (!isAuthenticated) return null;
  return <AppShell title="Mata Pelajaran"><main className="mx-auto max-w-6xl space-y-6"><div><h1 className="text-2xl font-semibold text-[var(--foreground)]">Mata Pelajaran Saya</h1><p className="mt-1 text-sm text-[var(--muted)]">Pelajari materi dan berlatih dengan pemeriksaan AI.</p></div>{error && <Alert type="error" message={error} onClose={() => setError('')} />}{!dashboard ? <div className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-8 text-sm text-[var(--muted)]">Memuat materi...</div> : <div className="space-y-5">{(dashboard.subjectAgenda || []).map((subject: any) => <section key={subject.id} className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm"><div className="border-b border-[var(--border)] pb-4"><h2 className="text-xl font-semibold text-[var(--foreground)]">{subject.subjectName}</h2><p className="text-sm text-[var(--muted)]">Tingkat {subject.gradeLevel} • {subject.lessons?.length || 0} materi</p></div><div className="mt-4 grid gap-4 lg:grid-cols-2">{(subject.lessons || []).map((lesson: any) => { const id = youtubeId(lesson.source); const url = id ? `https://www.youtube.com/embed/${id}?autoplay=1` : lesson.previewUrl; return <article key={lesson.id} className="rounded-lg border border-[var(--border)] bg-[var(--background)] p-4"><h3 className="font-semibold text-[var(--foreground)]">{lesson.title}</h3><p className="mt-1 text-sm text-[var(--muted)]">{lesson.week ? `Minggu ${lesson.week} • ` : ''}{lesson.description || 'Materi pembelajaran'}</p><div className="mt-4 flex flex-wrap gap-2"><Button type="button" variant="secondary" disabled={!url} onClick={() => url && setStudy({ title: lesson.title, url, type: id ? 'youtube' : 'pdf' })}>{id ? 'Tonton Video' : 'Buka PDF'}</Button><Button type="button" variant="secondary" onClick={() => void openPractice(lesson.id)} isLoading={aiLoading}>Latihan AI</Button></div></article>; })}</div>{(!subject.lessons || subject.lessons.length === 0) && <p className="mt-4 text-sm text-[var(--muted)]">Belum ada lesson.</p>}</section>)}</div>}
{study && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="flex h-[min(90vh,820px)] w-[min(94vw,1180px)] flex-col overflow-hidden rounded-xl bg-white shadow-2xl"><div className="flex shrink-0 items-center justify-between border-b px-4 py-3"><h2 className="font-semibold text-gray-900">{study.title}</h2><button type="button" onClick={() => setStudy(null)} className="rounded-lg p-2 text-2xl text-gray-500 hover:bg-gray-100" aria-label="Tutup">×</button></div><div className="min-h-0 flex-1 bg-gray-100 p-3">{study.type === 'youtube' ? <iframe title={study.title} src={study.url} className="h-full min-h-[300px] w-full rounded-lg" allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen /> : <iframe title={study.title} src={study.url} className="h-full min-h-[420px] w-full rounded-lg" />}</div></div></div>}
{practice && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-xl bg-[var(--surface)] p-5 shadow-2xl"><div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-semibold text-[var(--foreground)]">Latihan: {practice.lesson.title}</h2></div><button type="button" onClick={closePractice} className="text-2xl text-[var(--muted)]" aria-label="Tutup">×</button></div>{!result ? <><div className="mt-5 space-y-4">{practice.questions.map((question, index) => <div key={index} className="rounded-lg border border-[var(--border)] p-4"><div className="flex justify-between gap-3"><p className="font-medium text-[var(--foreground)]">{index + 1}. {question.questionText}</p><span className="shrink-0 text-xs text-blue-600">{question.points || 10} poin</span></div>{question.type === 'multiple_choice' ? <div className="mt-3 space-y-2">{(question.options || []).map((option, optionIndex) => <label key={optionIndex} className="flex gap-2 text-sm text-[var(--foreground)]"><input type="radio" name={`practice-${index}`} checked={answers[index] === String(optionIndex)} onChange={() => setAnswers((current) => ({ ...current, [index]: String(optionIndex) }))} />{option}</label>)}</div> : <textarea value={answers[index] || ''} onChange={(event) => setAnswers((current) => ({ ...current, [index]: event.target.value }))} rows={3} className="mt-3 w-full rounded-lg border border-[var(--border)] bg-[var(--background)] p-3 text-sm text-[var(--foreground)]" placeholder="Tulis jawaban Anda" />}</div>)}</div><div className="mt-5 flex justify-end"><Button type="button" onClick={() => void gradePractice()} isLoading={aiLoading}>Periksa</Button></div></> : <div className="mt-5"><div className="rounded-lg bg-blue-50 p-5 text-center"><p className="text-sm text-blue-700">Nilai Latihan</p><p className="mt-1 text-4xl font-bold text-blue-900">{result.percentage.toFixed(2)}%</p><p className="mt-1 text-sm text-blue-700">{result.score} / {result.maxScore} poin</p></div><div className="mt-4 space-y-3">{result.results.map((item, index) => <div key={index} className={`rounded-lg border p-4 ${item.correct ? 'border-green-200 bg-green-50' : 'border-red-200 bg-red-50'}`}><div className="flex justify-between gap-3"><p className="font-medium text-gray-900">Soal {index + 1}: {item.correct ? 'Benar' : 'Perlu dipelajari lagi'}</p><span className="text-sm font-semibold text-gray-700">{item.matchPercentage}% • {item.awardedPoints}/{item.maxPoints}</span></div>{!item.correct && <p className="mt-1 text-sm text-gray-700">{item.explanation}</p>}</div>)}</div><div className="mt-5 flex justify-end"><Button type="button" onClick={closePractice}>Selesai</Button></div></div>}</div></div>}
{aiLoading && <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/40 p-4"><div className="rounded-xl bg-[var(--surface)] px-8 py-7 text-center shadow-2xl"><div className="mx-auto h-10 w-10 animate-spin rounded-full border-4 border-blue-100 border-t-blue-600" /><p className="mt-4 font-semibold text-[var(--foreground)]">AI sedang memproses...</p></div></div>}
</main></AppShell>;
}
